/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
#include "ProjectHeads.h"

void ProjectsObj::Project2Calc(int upperLimit)
{
    int runningTotal = 2;
    int a = 1;
    int b = 2;
    int c;
    while (b < upperLimit)
    {
        c = a + b;
        a = c + b;
        b = c + a;

        if (a % 2 == 0 && a < upperLimit)
            runningTotal += a;
        if (b % 2 == 0 && b < upperLimit)
            runningTotal += b;
        if (c % 2 == 0 && c < upperLimit)
            runningTotal += c;
    }
    std::cout << "Sum of even Fibonacci numbers up to limit: " << runningTotal << "\n";
}